### ISSUE TITLE
processTransaction not working for user paying online

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#91] opened 2020-03-24 09:58 UTC
When a user makes a payment/funds his account online, the processTransaction mutation ought to run to complete the user's funding after a successful payment callback is returned from paystack.
The mutation is being called but returns with this error. This is not supposed to be the case, it should check for the transaction_medium if its ONLINE it should allow the transaction to get approved

Uncaught (in promise) Error: GraphQL error: You are not authorized to access ProcessTransaction
    at new ApolloError (bundle.esm.js?74ca:60)
    at QueryManager.eval (bundle.esm.js?74ca:980)
    at step (tslib.es6.js?9ab4:97)
    at Object.eval [as next] (tslib.es6.js?9ab4:78)
    at eval (tslib.es6.js?9ab4:71)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js?9ab4:67)
    at Object.next (bundle.esm.js?74ca:972)
    at notifySubscription (Observable.js?a7b2:130)
    at onNotify (Observable.js?a7b2:165)

**Comment by omadoyeabraham** [comment] 2020-04-13 12:19
Duplicate of https://github.com/omadoyeabraham/springverse-api/issues/83

**Closed as completed by omadoyeabraham** 2020-04-13 12:19 UTC
Labels: bug
